In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\loq\anaconda3\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\loq\anaconda3\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\loq\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\loq\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\loq\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:
info = {
    "Name": ["Rahul","Ankita","Jibitesh"],
    "CGPA": [9.5,10,9.9]
}
df = pd.DataFrame(info)
df

       Name  CGPA
0     Rahul   9.5
1    Ankita  10.0
2  Jibitesh   9.9

In [5]:
df = pd.DataFrame(info, ["A","B","C"])
df

       Name  CGPA
A     Rahul   9.5
B    Ankita  10.0
C  Jibitesh   9.9

# Series

In [9]:
s = pd.Series([1,2,3,4,5])
print(s)
print(type(s))

#index
print(s[0])
print(s[1])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>
1
2

In [32]:
s = pd.Series([23,24,25,26,"abc"], index=["Ankita","Bear","Bob","Charlie",25])
print(s)

print(s["Ankita"])
#print(s[0])  #Error
print(s.index)

#NOTE: To get the dtype as fully str or int the whole list should be homogenous
#otherwise it will give an object

Ankita      23
Bear        24
Bob         25
Charlie     26
25         abc
dtype: object
23
Index(['Ankita', 'Bear', 'Bob', 'Charlie', 25], dtype='object')

In [33]:
#Vectorized Operation
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])
print(s1+s2)

#Mutable(Immutable size)
s1[0] = 100
print(s1)

changed_s1 = s1.drop(0)
print(changed_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

# DataFrame

In [42]:
info = {
    "Name": ["Ankita","Bob","Eve"],
    "Age": [23,24,25],
    "GPA": [9.5,8.6,7.2]
}
df = pd.DataFrame(info)
print(df)
print(type(df))
print(df.index)
print(df.columns)

     Name  Age  GPA
0  Ankita   23  9.5
1     Bob   24  8.6
2     Eve   25  7.2
<class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='str')

In [36]:
df

     Name  Age  GPA
0  Ankita   23  9.5
1     Bob   24  8.6
2     Eve   25  7.2

#### Creation of DataFrame

In [43]:
#list of list
df = pd.DataFrame([["Adam",23],["Bob",23],["Eve",23]], columns=["Name","Age"])
print(df)

   Name  Age
0  Adam   23
1   Bob   23
2   Eve   23

In [45]:
#np array

import numpy as np
np_arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(np_arr,columns = ["A","B","C"])
df

   A  B  C
h  1  2  3
y  4  5  6

# CSV Data

In [46]:
df = pd.read_csv("employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [52]:
df1 = pd.read_json("employee_data.json")
print(df1, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

# DataFrame Methods

In [53]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [54]:
df.head() #starting 5 rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [55]:
df.tail() #trailing 5 rows

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [56]:
df.tail(2)

   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000

In [57]:
df.sample() #random row

   ID Name  Age Department  Salary
8   9  Ian   35         IT   75000

In [58]:
df.sample(5)

   ID     Name  Age Department  Salary
8   9      Ian   35         IT   75000
7   8   Hannah   26  Marketing   47000
2   3  Charlie   28    Finance   48000
4   5      Eva   38         IT   65000
1   2      Bob   32         IT   72000

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 628.0 bytes

In [60]:
df.shape

(10, 5)

In [62]:
df.describe()
#numerical statistics

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [63]:
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [65]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='str')